services:
  test-database:
    image: postgres:17
    container_name: test-database
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5436:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    networks:
      - task-network

  app:
    build:
      dockerfile: Dockerfile
    container_name: test-task-container
    ports:
      - "8000:8000"
    depends_on:
      - test-database
    env_file: ./env
    networks:
      - task-network
    command: > 
      sh -c "alembic upgrade head"

volumes:
  test_db_data:

networks:
  task-network:
    driver: bridge